name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  relayer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: make yrly
